name:                hamtulz
version:             0.0.0.0
github:              "majkrzak/hamtulz"
license:             ISC
author:              "Piotr Majkrzak"

dependencies:
- base >= 4.7 && < 5
- parsec
- time
- yaml
- text
- bytestring
- template-haskell
- xdg-basedir
- lens
- data-default

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- TypeOperators
- DefaultSignatures
- LambdaCase
- TemplateHaskell
- ScopedTypeVariables
- StandaloneDeriving
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - empty

executables:
  wsjtx2log:
    main: Main.hs
    source-dirs: app/wsjtx2log
    dependencies:
      - hamtulz
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  log2adif:
    main: Main.hs
    source-dirs: app/log2adif
    dependencies:
      - hamtulz
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  check_log:
    main: Main.hs
    source-dirs: app/check_log
    dependencies:
      - hamtulz
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  add_log:
    main: Main.hs
    source-dirs: app/add_log
    dependencies:
      - hamtulz
      - empty
      - monomer
      - lens
      - text-show
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

internal-libraries:
  empty:
    source-dirs: lib/empty
