name:                hamtulz
version:             0.0.0.0
github:              "majkrzak/hamtulz"
license:             ISC
author:              "Piotr Majkrzak"

dependencies:
- base >= 4.7 && < 5
- parsec
- time
- yaml
- text
- bytestring
- template-haskell
- xdg-basedir

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- FlexibleContexts
- LambdaCase
- TemplateHaskell
- ScopedTypeVariables
- StandaloneDeriving

library:
  source-dirs: src

executables:
  wsjtx2log:
    main: Main.hs
    source-dirs: app/wsjtx2log
    dependencies:
      - hamtulz
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  log2adif:
    main: Main.hs
    source-dirs: app/log2adif
    dependencies:
      - hamtulz
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hamtulz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamtulz
