name:                hamtulz
version:             0.0.0.0
github:              "majkrzak/hamtulz"
license:             ISC
author:              "Piotr Majkrzak"

dependencies:
- base >= 4.7 && < 5
- parsec
- time
- yaml
- text
- bytestring
- template-haskell
- xdg-basedir
- lens
- data-default
- containers

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- TypeOperators
- DefaultSignatures
- LambdaCase
- TemplateHaskell
- ScopedTypeVariables
- StandaloneDeriving
- OverloadedStrings
- ImportQualifiedPost
- MultiParamTypeClasses
- RankNTypes
- ImpredicativeTypes

library:
  source-dirs: src
  dependencies:
  - hamtulz-empty
  - hamtulz-lens-helper
  - hamtulz-adi
  - hamtulz-adif
  - hamtulz-log
  - hamtulz-radio

executables:
  wsjtx2log:
    main: Main.hs
    source-dirs: app/wsjtx2log
    dependencies:
    - hamtulz
    - hamtulz-adi
    - hamtulz-adif
    - hamtulz-log
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  log2adif:
    main: Main.hs
    source-dirs: app/log2adif
    dependencies:
    - hamtulz
    - hamtulz-adif
    - hamtulz-lens-helper
    - hamtulz-empty
    - hamtulz-log
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  add_log:
    main: Main.hs
    source-dirs: app/add_log
    dependencies:
    - hamtulz
    - hamtulz-adif
    - hamtulz-lens-helper
    - hamtulz-empty
    - hamtulz-log
    - monomer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  check_log:
    main: Main.hs
    source-dirs: app/check_log
    dependencies:
    - hamtulz
    - hamtulz-lens-helper
    - hamtulz-empty
    - hamtulz-log
    - hamtulz-valid
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

internal-libraries:
  hamtulz-valid:
    source-dirs: lib/valid
    exposed-modules:
    - Data.Valid
  hamtulz-empty:
    source-dirs: lib/empty
    exposed-modules:
    - Data.Empty
  hamtulz-lens-helper:
    source-dirs: lib/lens-helper
    exposed-modules:
    - Control.Lens.Helper
    dependencies:
    - hamtulz-empty
  hamtulz-yaml-helper:
    source-dirs: lib/yaml-helper
    exposed-modules:
    - Data.Yaml.Helper
  hamtulz-adi:
    source-dirs: lib/adi
    exposed-modules:
    - Data.Adi
    dependencies:
    - hamtulz-empty
    - hamtulz-valid
  hamtulz-adif:
    source-dirs: lib/adif
    exposed-modules:
    - Data.Adif
    dependencies:
    - hamtulz-empty
    - hamtulz-adi
  hamtulz-radio:
    source-dirs: lib/radio
    exposed-modules:
    - Data.Radio
    dependencies:
    - hamtulz-empty
    - hamtulz-valid
    - hamtulz-lens-helper
    - hamtulz-yaml-helper
  hamtulz-log:
    source-dirs: lib/log
    exposed-modules:
    - Data.Log
    dependencies:
    - hamtulz-empty
    - hamtulz-valid
    - hamtulz-lens-helper
    - hamtulz-yaml-helper
    - hamtulz-adif
    - hamtulz-radio

tests:
  test-adi:
    main: Main.hs
    source-dirs: test/adi
    dependencies:
    - hamtulz-valid
    - hamtulz-adi
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
    - tasty-hunit
    - smallcheck
    - QuickCheck
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
