name:                hamtulz
version:             0.0.0.0
github:              "majkrzak/hamtulz"
license:             ISC
author:              "Piotr Majkrzak"

dependencies:
- base >= 4.7 && < 5
- parsec
- time
- yaml
- text
- bytestring
- template-haskell
- xdg-basedir
- lens
- data-default

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- TypeOperators
- DefaultSignatures
- LambdaCase
- TemplateHaskell
- ScopedTypeVariables
- StandaloneDeriving
- OverloadedStrings
- ImportQualifiedPost
- MultiParamTypeClasses
- RankNTypes
- ImpredicativeTypes

library:
  source-dirs: src
  dependencies:
  - hamtulz-empty
  - hamtulz-lens-helper
  - hamtulz-adi
  - hamtulz-adif

executables:
  wsjtx2log:
    main: Main.hs
    source-dirs: app/wsjtx2log
    dependencies:
    - hamtulz
    - hamtulz-adi
    - hamtulz-adif
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  log2adif:
    main: Main.hs
    source-dirs: app/log2adif
    dependencies:
    - hamtulz
    - hamtulz-adif
    - hamtulz-lens-helper
    - hamtulz-empty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  check_log:
    main: Main.hs
    source-dirs: app/check_log
    dependencies:
    - hamtulz
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  add_log:
    main: Main.hs
    source-dirs: app/add_log
    dependencies:
    - hamtulz
    - hamtulz-empty
    - monomer
    - lens
    - text-show
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

internal-libraries:
  hamtulz-valid:
    source-dirs: lib/valid
  hamtulz-empty:
    source-dirs: lib/empty
  hamtulz-lens-helper:
    source-dirs: lib/lens-helper
    dependencies:
    - hamtulz-empty
  hamtulz-adi:
    source-dirs: lib/adi
    dependencies:
    - hamtulz-empty
    - hamtulz-valid
  hamtulz-adif:
    source-dirs: lib/adif
    dependencies:
    - hamtulz-empty
    - hamtulz-adi

tests:
  test-adi:
    main: Main.hs
    source-dirs: test/adi
    dependencies:
    - hamtulz-valid
    - hamtulz-adi
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
    - tasty-hunit
    - smallcheck
    - QuickCheck
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
